server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.52.121
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cart?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  rabbitmq:
    host: 192.168.52.121
    port: 5672
    username: dawnlee
    password: 123456
    virtualHost: /dawnlee
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 6
  task:
    execution:
      thread-name-prefix: gmall-cart-
      pool:
        core-size: 200
        max-size: 500
        queue-capacity: 2000
        keep-alive: 60s
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
feign:
  sentinel:
    enabled: true
jwt:
  pubFilePath: D:\李先锋\project-dawn\rsa\rsa.pub #不用局部过滤器, 登不登陆都可使用购物车, 所以需要自己解析token, 解析成功用userId,不成功用user-key
  expire: 259200
  cookieName: GMALL-TOKEN
  userKey: user-key
mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id策略: 默认数据库自增