server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
    content-type: text/html
    mode: LEGACYHTML5
feign:
  sentinel:
    enabled: true
threadPool:
  corePoolSize: 100
  maximumPoolSize: 500
  keepAliveTime: 60
  blockingQueueSize: 2000